"""add is_claimed in Service

Revision ID: 0f2f0cb3cafe
Revises: cbdd0767df9c
Create Date: 2017-07-11 10:39:29.537797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f2f0cb3cafe'
down_revision = 'cbdd0767df9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('is_claimed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Counsels_timestamp'), table_name='Counsels')
    # ### end Alembic commands ###
