"""add Hospital

Revision ID: 15db7fb2c361
Revises: 11c7e2160b6b
Create Date: 2017-06-13 12:49:54.215414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15db7fb2c361'
down_revision = '11c7e2160b6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospitals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('doctor', sa.String(length=8), nullable=True),
    sa.Column('phone', sa.String(length=16), nullable=True),
    sa.Column('address', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hospitals')
    # ### end Alembic commands ###
