"""add price_text in price

Revision ID: 38f71bc6cb06
Revises: de731d3fc7f5
Create Date: 2017-07-21 09:28:20.983827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38f71bc6cb06'
down_revision = 'de731d3fc7f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('price_text', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'price_text')
    # ### end Alembic commands ###
