"""add is_confirmed in Event

Revision ID: 5b77d28cba9c
Revises: 332aa7a648ca
Create Date: 2017-07-17 01:01:00.095871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b77d28cba9c'
down_revision = '332aa7a648ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('is_confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'is_confirmed')
    # ### end Alembic commands ###
