"""add is_selected in Offer

Revision ID: 62d488912b78
Revises: fea35f6f439e
Create Date: 2017-07-16 19:13:43.050285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62d488912b78'
down_revision = 'fea35f6f439e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('is_selected', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offers', 'is_selected')
    # ### end Alembic commands ###
