"""add some column in HospitalAd

Revision ID: a36adbdb8fd3
Revises: 5b77d28cba9c
Create Date: 2017-07-17 01:26:44.484703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a36adbdb8fd3'
down_revision = '5b77d28cba9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hospital_ads', sa.Column('hits', sa.Integer(), nullable=True))
    op.add_column('hospital_ads', sa.Column('start_date', sa.DateTime(), nullable=True))
    op.add_column('hospital_ads', sa.Column('term', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hospital_ads', 'term')
    op.drop_column('hospital_ads', 'start_date')
    op.drop_column('hospital_ads', 'hits')
    # ### end Alembic commands ###
