"""add Category table

Revision ID: a7b2018326fc
Revises: 0f2f0cb3cafe
Create Date: 2017-07-11 14:18:14.806690

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'a7b2018326fc'
down_revision = '0f2f0cb3cafe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('categories')
    op.drop_table('hospitalAds')
    op.drop_table('counsels')
    op.create_table('categories',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=8), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('hospitalAds',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('hospital_id', sa.Integer(), nullable=True),
                    sa.Column('name', sa.String(length=64), nullable=True),
                    sa.Column('is_hospital_ad', sa.Boolean(), nullable=True),
                    sa.Column('is_confirmed', sa.Boolean(), nullable=True),
                    sa.Column('timestamp', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_hospitalAds_timestamp'), 'hospitalAds', ['timestamp'], unique=False)
    op.create_table('counsels',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('lawyer_id', sa.Integer(), nullable=True),
                    sa.Column('body', sa.Text(), nullable=True),
                    sa.Column('timestamp', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['lawyer_id'], ['lawyers.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_counsels_timestamp'), 'counsels', ['timestamp'], unique=False)
    op.drop_table('HospitalAds')
    op.drop_table('Counsels')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Counsels',
                    sa.Column('id', sa.INTEGER(), nullable=False),
                    sa.Column('user_id', sa.INTEGER(), nullable=True),
                    sa.Column('lawyer_id', sa.INTEGER(), nullable=True),
                    sa.Column('body', sa.TEXT(), nullable=True),
                    sa.Column('timestamp', sa.DATETIME(), nullable=True),
                    sa.ForeignKeyConstraint(['lawyer_id'], ['lawyers.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('HospitalAds',
                    sa.Column('id', sa.INTEGER(), nullable=False),
                    sa.Column('hospital_id', sa.INTEGER(), nullable=True),
                    sa.Column('name', sa.VARCHAR(length=64), nullable=True),
                    sa.Column('is_hospital_ad', sa.BOOLEAN(), nullable=True),
                    sa.Column('is_confirmed', sa.BOOLEAN(), nullable=True),
                    sa.Column('timestamp', sa.DATETIME(), nullable=True),
                    sa.CheckConstraint('is_confirmed IN (0, 1)'),
                    sa.CheckConstraint('is_hospital_ad IN (0, 1)'),
                    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.drop_index(op.f('ix_counsels_timestamp'), table_name='counsels')
    op.drop_table('counsels')
    op.drop_index(op.f('ix_hospitalAds_timestamp'), table_name='hospitalAds')
    op.drop_table('hospitalAds')
    op.drop_table('categories')
    # ### end Alembic commands ###
