"""delete has madal in hospital

Revision ID: b7db0b11ab43
Revises: cf96d234bbd7
Create Date: 2017-10-03 19:29:46.535834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7db0b11ab43'
down_revision = 'cf96d234bbd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hospitals', 'has_medal_2')
    op.drop_column('hospitals', 'has_medal_1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hospitals', sa.Column('has_medal_1', sa.BOOLEAN(), nullable=True))
    op.add_column('hospitals', sa.Column('has_medal_2', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
