"""add recommend in user

Revision ID: bc59ffeba171
Revises: 45cf1c48f3ba
Create Date: 2017-07-21 15:16:01.405569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc59ffeba171'
down_revision = '45cf1c48f3ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('recommend_user_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'recommend_user_id')
    # ### end Alembic commands ###
