"""add social_id in User

Revision ID: ccb21534a7d0
Revises: 5c5570a59dd3
Create Date: 2017-06-08 14:48:55.349156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccb21534a7d0'
down_revision = '5c5570a59dd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('social_id', sa.String(length=64), nullable=True))
    op.drop_index('ix_users_username', table_name='users')
    op.create_unique_constraint(None, 'users', ['social_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index('ix_users_username', 'users', ['username'], unique=1)
    op.drop_column('users', 'social_id')
    # ### end Alembic commands ###
