"""add price in Offer

Revision ID: fea35f6f439e
Revises: 5faceeadaec3
Create Date: 2017-07-16 19:02:17.250398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fea35f6f439e'
down_revision = '5faceeadaec3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('price', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offers', 'price')
    # ### end Alembic commands ###
